# Generated by Django 4.2.1 on 2023-05-30 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_country_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='weather',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, null=True)),
                ('rating', models.IntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.country')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('tel_number', models.CharField(max_length=20)),
                ('tour', models.ManyToManyField(to='tours.tour')),
            ],
        ),
    ]
