# Generated by Django 4.2.1 on 2023-06-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_country_weather_hotel_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
