# Generated by Django 4.2.1 on 2023-06-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
