# Generated by Django 4.2.1 on 2023-06-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_tour_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='tour',
            field=models.ManyToManyField(null=True, to='tours.tour'),
        ),
    ]
