# Generated by Django 4.2.1 on 2023-06-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_remove_tour_category_tour_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugify_name',
            field=models.CharField(auto_created='djangodbmodelsfieldscharfield', db_index=True, default='djangodbmodelsfieldscharfield', max_length=200),
        ),
    ]
