# Generated by Django 4.2.1 on 2023-06-02 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_alter_category_slugify_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='country',
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.country'),
        ),
    ]
