# Generated by Django 4.2.1 on 2023-06-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0017_remove_tour_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.country'),
        ),
    ]
