# Generated by Django 4.2.1 on 2023-06-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0018_tour_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=7)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'ordering': ['cost']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='tour',
        ),
        migrations.AlterField(
            model_name='client',
            name='tel_number',
            field=models.CharField(max_length=20, verbose_name='telephone number'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating (stars)'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time of creation'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='last update'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateTimeField(null=True)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tours.term')),
                ('tour', models.ManyToManyField(null=True, to='tours.tour')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='ticket',
            field=models.ManyToManyField(null=True, to='tours.ticket'),
        ),
    ]
