# Generated by Django 4.2.1 on 2023-06-03 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_term_alter_category_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tour',
        ),
        migrations.AddField(
            model_name='ticket',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tour'),
        ),
    ]
